// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/GameRoom copy.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    GameCanvas: typeof import('./src/components/GameCanvas.vue')['default']
    GameRoom: typeof import('./src/components/GameRoom.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
