version: '3.4'

services:
  application.manager.api:
    image: ${DOCKER_REGISTRY-}applicationmanagerapi
    build:
      context: .
      dockerfile: Application/Application.Manager.Api/Dockerfile
  application.game.server:
    image: ${DOCKER_REGISTRY-}applicationgameserver
    build:
      context: .
      dockerfile: Application/Application.Game.Server/Dockerfile

