version: '3.9'
name: snake-game
services:
  application.manager.api:
    image: ${DOCKER_REGISTRY-}snake-game/manager-api
    build:
      context: .
      dockerfile: Application/Application.Manager.Api/Dockerfile
    depends_on:
        rabbitmq:
            condition: service_healthy
    profiles:
        - server-core-plus-local-enviroment
        - server-core
        - server-core-plus-ui-angular
        - server-core-plus-local-enviroment-plus-ui-angular
    networks:
      - snake-game
  application.game.server:
    image: ${DOCKER_REGISTRY-}snake-game/server
    build:
      context: .
      dockerfile: Application/Application.Game.Server/Dockerfile
    depends_on:
        - application.manager.api
    profiles:
        - server-core-plus-local-enviroment
        - server-core
        - server-core-plus-ui-angular
        - server-core-plus-local-enviroment-plus-ui-angular
    networks:
      - snake-game
  application.ui.angular:
    image: ${DOCKER_REGISTRY-}snake-game/ui/angular
    build:
      context: Application/Application.Ui.Angular
      dockerfile: Dockerfile
    depends_on:
      application.manager.api:
        condition: service_started
      application.game.server:
        condition: service_started
    profiles:
        - ui-angular
        - server-core-plus-ui-angular
        - server-core-plus-local-enviroment-plus-ui-angular
    networks:
      - snake-game
  redis:
    hostname: redis
    image: redis
    networks:
      - snake-game
    profiles:
        - local-enviroment
        - server-core-plus-local-enviroment
        - server-core-plus-local-enviroment-plus-ui-angular
  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    networks:
      - snake-game
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
    profiles:
        - local-enviroment
        - server-core-plus-local-enviroment
        - server-core-plus-local-enviroment-plus-ui-angular
  rabbitmq:
    image: rabbitmq:management
    container_name: 'rabbitmq'
    networks:
      - snake-game
    ports:
        - 15672:15672
    profiles:
        - local-enviroment
        - server-core-plus-local-enviroment
        - server-core-plus-local-enviroment-plus-ui-angular
networks:
  snake-game:
    driver: bridge
