name: Docker Build and Push Application.Ui.Angular

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    paths-ignore: 
      - '**/*.md'
  pull_request:
    branches:
      - 'main'
  
jobs:
  build:
    env:
      DOCKER_ROOT_CONTEXT: 'src/Application/Application.Game.Server'
      DOCKER_REPOSITORY_NAME: 'dev-vinicius-andrade/snake-game/application/game/server'
      DOCKER_REGISTRY: ${{ secrets.CODESCOVERY_REGISTRY }}
      DOCKER_USERNAME: ${{ secrets.CODESCOVERY_REGISTRY_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.CODESCOVERY_REGISTRY_TOKEN }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY_NAME }}
        tags: |
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}.{{patch}}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}
    - name: Build
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        file: ${{env.DOCKER_ROOT_CONTEXT}}/Dockerfile
        context: ${{env.DOCKER_ROOT_CONTEXT}}
        tags: |
          ${{ steps.meta.outputs.tags }}
         
